[package]
name = "thrpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["macros","rt-multi-thread"] }
toml = "0.5.8"
serde = { version = "1.0.135", features = ["derive"] }
rand = "0.8.4"
anyhow = "1.0.53"
thiserror = "1.0.30"
once_cell = "1.9.0"
tracing = "0.1.29"
[dependencies.serenity]
default-features = false
features = [
    "builder",
    "collector",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "cache"
]
version = "0.10.10"
[dependencies.redis]
version = "0.21.5"
features = [
    "tokio-comp",
    "tokio-native-tls-comp"
]
[dependencies.sea-orm]
version = "0.5.0"
features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros"
]
default-features = false
