[package]
name = "test-kani"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
youtube_dl = "0.6.3"
songbird = "0.2.0"
tracing = "0.1.27"
tokio = { version = "1.6.0", features = ["macros","rt-multi-thread"] }
[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "cache"
]
version = "0.10.9"

