version: "3.8"
services: 
  postgres:
    restart: always
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: thrpg
    volumes:
      - ./postgres:/var/lib/postgres/data
      - ./sqls:/docker-entrypoint-initdb.d

  redis:
    image: redis:6-alpine
    restart: always
    healthcheck:
      test: ["CMD","redis-cli","ping"]
    volumes:
      - ./redis:/data

  bot:
    build: .
#    environment:
#      - RUST_BACKTRACE=1
    command: ./bot
    restart: always
    depends_on:
      - postgres
      - redis

