version: "3.8"
services: 
  postgres:
    restart: always
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: thrpg
      POSTGRES_USER: thrpg
      POSTGRES_PASSWORD: thrpg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgres/data

  redis:
    image: redis:6-alpine
    restart: always
    healthcheck:
      test: ["CMD","redis-cli","ping"]
    volumes:
      - ./redis:/data

  bot:
    build: .
    command: ./bot
    restart: always
    depends_on:
      - postgres
      - redis

