[charabase]
name = "霧雨魔理沙"
power = 110
guard = 90
speed = 110
hp = 100
mp = 100

[[attack]]
name = "マスタースパーク"
damage = 90
hit_rate = 0.9

[meta]
levelup_exp = "Normal"
species_type = "Magician"
get_exp = 100
skill_type = "Effort"
