[charabase]
name = "十六夜咲夜"
power = 105
guard = 100
speed = 115
hp = 100
mp = 100

[[attack]]
name = "殺人ドール"
damage = 80
hit_rate = 0.9

[meta]
levelup_exp = "Normal"
species_type = "Maid"
get_exp = 100
skill_type = "Effort"
