[charabase]
name = "十六夜咲夜"
power = 100
guard = 100
speed = 100
hp = 100
mp = 100

[[attack]]
name = "夢想封印"
damage = 70
hit_rate = 0.9

[meta]
levelup_exp = "Normal"
species_type = "Human"
species_description = "メイド長"
get_exp = 100
skill_type = "Lucky"
